### ISSUE TITLE
send_error is never triggered

### ISSUE THREAD

**Issue by giom-l** [cloudreach/aws-lambda-es-cleanup#28]
The sns_alert is not used anywhere.

**Comment by giuliocalzo** [comment]
Hi @gocho1 you're right `sns_alert` is a leftover from the initial dev phase.
to handle in a proper way the Lambda Error you need to change the `serverless.yml` config adding the following yaml key

`onError: arn:aws:sns:us-east-1:XXXXXX:sns-topic # Optional SNS topic `
[Official Doc](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/)


or in Terraform using `dead_letter_config` as described in the [Terraform Docs](https://www.terraform.io/docs/providers/aws/r/lambda_function.html#dead_letter_config)

This feature is not enabled by default in the repo due to the lambda error handling is not part of the main scope of this repo.
Different team prefer to handle the lambda error in many different ways,  I will remove the leftover python code asap.
