### ISSUE TITLE
ValueError: You can only send PreparedRequests.

### ISSUE THREAD

**Issue by akhilteej** [cloudreach/aws-lambda-es-cleanup#29]
Hi, I'm using in lambda function. From few days I'm facing below issue.

You can only send PreparedRequests.: ValueError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 180, in lambda_handler
for index in es.get_indices():
File "/var/task/lambda_function.py", line 165, in get_indices
return self.send_to_es("/_cat/indices")
File "/var/task/lambda_function.py", line 119, in send_to_es
res = session.send(preq)
File "/var/runtime/botocore/vendored/requests/sessions.py", line 551, in send
raise ValueError('You can only send PreparedRequests.')
ValueError: You can only send PreparedRequests.

**Comment by RmMsr** [comment]
I see the same error. We use the latest `es-cleanup.py` code. All available Python versions (2.7, 3.6, 3.7) seem to be affected.

I traced the error down to the [vendored requests Session class](https://github.com/boto/botocore/blob/master/botocore/vendored/requests/sessions.py#L551). I am no good with Python, but I wonder how this ever worked.

[Relevant code](https://github.com/cloudreach/aws-lambda-es-cleanup/blob/master/es-cleanup.py#L125):

```
            req = AWSRequest(
                method=method,
                url="https://{}{}".format(
                    self.cfg["es_endpoint"], quote(path)),
                data=json.dumps(payload),
                params={"format": "json"},
                headers=headers)
#...
            try:
                preq = req.prepare()
                session = Session()
                res = session.send(preq)
```
[`AWSRequest.prepare()`](https://github.com/boto/botocore/blob/master/botocore/awsrequest.py#L495) seems to create an instance of `AWSPreparedRequest(object)`. Unfortunately `Session.send(preq)` fails with the error above if the preq is not an `PreparedRequest`.

This logic has been [fixed in the upstream](https://github.com/psf/requests/commit/ae1ac2d4e075fddf67b81e9aa19fbaf6e2c40941) years ago but never got into botocore.

**Update**: The use of the vendored requests lib is no longer a valid approad. See [botocore 1.11 release notes](https://botocore.amazonaws.com/v1/documentation/api/latest/index.html#upgrading-to-1-11-0)

**Comment by DavidWittman** [comment]
This can be fixed with:

``` diff
diff --git a/es-cleanup.py b/es-cleanup.py
index 0dd1321..06a7928 100644
--- a/es-cleanup.py
+++ b/es-cleanup.py
@@ -12,8 +12,8 @@ import datetime
 from botocore.auth import SigV4Auth
 from botocore.awsrequest import AWSRequest
 from botocore.credentials import create_credential_resolver
+from botocore.httpsession import URLLib3Session
 from botocore.session import get_session
-from botocore.vendored.requests import Session
 import sys
 if sys.version_info[0] == 3:
     from urllib.request import quote
@@ -121,7 +121,7 @@ class ES_Cleanup(object):

             try:
                 preq = req.prepare()
-                session = Session()
+                session = URLLib3Session()
                 res = session.send(preq)
                 if res.status_code >= 200 and res.status_code <= 299:
                     return json.loads(res.content)
```

Opening a PR here momentarily.

**Comment by BruceABeitman** [comment]
Can confirm, had this issue. @DavidWittman's solution fixed it for me. Thanks!

**Comment by giuliocalzo** [comment]
Uhmm interesting... This issue was never detected before!
I'm investing about that

**Comment by giuliocalzo** [comment]
looking to AWS official dock
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

python3.6 uses  `boto3-1.7.74` and `botocore-1.10.74`
and 
python3.7 uses `boto3-1.9.42` and `botocore-1.12.42`

@BruceABeitman @DavidWittman can you please confirm which python version are you using?

cheers

**Comment by DavidWittman** [comment]
Python 3.6 here

**Comment by BruceBeitman** [comment]
Python 3.7, but changing the lambda to Python 2.7 seems to not affect it. 

We've had this lambda running everyday for about a year, and it started failing on the 21st midnight UTC. Which makes me believe AWS deprecated something on their end causing some part of botocore to not work as it used to? Just my best guess as of now.

**Comment by BruceABeitman** [comment]
Python 3.7, but changing the lambda to python 2.7 doesn't seem to affect it either.

We've had this lambda running every day for the past year or so without issue until the 21st. Which makes me believe AWS changed something on their end which deprecated something that `botocore.vendored.requests` was using in the session object? Just my best guess.

**Comment by giuliocalzo** [comment]
the change of botocore is implemented in  botocore==1.11
I'm expecting no problem on python3.6 and issue on python3.7
I will test today to reproduce the issue

**Comment by giuliocalzo** [comment]
@DavidWittman can you confirm if with python3.6 happen?

**Comment by DavidWittman** [comment]
@giuliocalzolari Yes, that's the version under which I was originally having this issue. #30 fixed it for me.

**Comment by giuliocalzo** [comment]
Thanks for your support @DavidWittman just merged!
